version: '3.7'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./services/backend:/usr/src/backend
    ports:
      - 1234:1234
    environment:
      - DATABASE_URL=postgresql://root:Allblackscup_01@stock-rds-db.ck01jddttrnr.ap-southeast-2.rds.amazonaws.com:5432/stock_announcement_db

  # frontend:
  #   build:
  #     context: ./services/frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './services/frontend/ui:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 8080:8080
  
  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - 8080:8080
    depends_on:
      - backend