version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 1234:1234
    networks:
      - mynet

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - './frontend/ui:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 8080:8080

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    container_name: web_server
    ports:
      - 80:80
    # environment:
    #   - API_URL=backend:1234
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

