version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 1234:1234
    networks:
      - mynet

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    container_name: web_server
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

