version: '3.7'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/backend/entrypoint.sh']
    volumes:
      - ./services/backend:/usr/src/backend
    ports:
      - 1234:5000
    environment:
      - QUART_ENV=development
      - DATABASE_URL=postgresql://root:Allblackscup_01@stock-rds-db.ck01jddttrnr.ap-southeast-2.rds.amazonaws.com:5432/stock_announcement_db
    networks:
      - api_bridge

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    volumes:
      - './services/frontend/ui:/app'
      - '/app/node_modules'
    ports:
      - 3007:8080
    environment:
      - NODE_ENV=development
      - BACKEND_SERVICE_URL=http://127.0.0.1:1234
      - VUE_GATEWAY_URL=http://127.0.0.1:3007
    networks:
      - api_bridge

networks:
  api_bridge:
    driver: bridge
