out:
  LOGS: logs

db:
  user: doadmin
  password: AVNS_93AZAKgiJVU7aJEccYd
  host: stock-announcement-db-do-user-13808930-0.b.db.ondigitalocean.com
  port: 25060
  name: defaultdb

timeout: 60

best_params:
  changepoint_prior_scale: 0.001
  seasonality_prior_scale: 12
  seasonality_mode: 'multiplicative'
